import type { Ticket, Notifications } from "./types";
import type { User } from "./types";

export const SubscriptionBreakdownData = [
    { name: "Simple", value: 120, color: "#065F5B" },
    { name: "Plus", value: 15, color: "#F4B400" },
    { name: "Premium", value: 8, color: "#EF4444" },
];

export const ClientDistributionData = [
    { state: "Florida", clients: 15 },
    { state: "New York", clients: 10 },
    { state: "Texas", clients: 10 },
    { state: "California", clients: 8 },
    { state: "Illinois", clients: 5 },
    { state: "Washington", clients: 4 },
    { state: "Nevada", clients: 3 },    
    { state: "Oregon", clients: 2 },
    { state: "Utah", clients: 2 },
    { state: "Arizona", clients: 1 },
];

// tickets
export const tickets: Ticket[] = [
    {
        ticketId: "#T-3827",
        submittedBy: "Meera S.",
        requested: "Organisation",
        issueType: "Sync Error",
        raisedOn: "07 Aug, 2025",
        priority: "High",
        status: "Open",
        lastUpdated: "10 min ago",
    },
    {
        ticketId: "#T-3784",
        submittedBy: "John D.",
        requested: "Internal",
        issueType: "AI Suggestion Issue",
        raisedOn: "29 Jul, 2025",
        priority: "Medium",
        status: "Open",
        lastUpdated: "1 hour ago",
    },
    {
        ticketId: "#T-3751",
        submittedBy: "Aarav K.",
        requested: "Organisation",
        issueType: "Payroll Mismatch",
        raisedOn: "25 Jul, 2025",
        priority: "High",
        status: "Open",
        lastUpdated: "3 hours ago",
    },
    {
        ticketId: "#T-3729",
        submittedBy: "Sophia L.",
        requested: "Internal",
        issueType: "Tax Calculation Error",
        raisedOn: "22 Jul, 2025",
        priority: "High",
        status: "Closed",
        lastUpdated: "1 day ago",
    },
    {
        ticketId: "#T-3698",
        submittedBy: "Rohan P.",
        requested: "Organisation",
        issueType: "Late Salary Credit",
        raisedOn: "20 Jul, 2025",
        priority: "Medium",
        status: "Open",
        lastUpdated: "2 days ago",
    },
    {
        ticketId: "#T-3665",
        submittedBy: "Emily R.",
        requested: "Internal",
        issueType: "Employee Onboarding Issue",
        raisedOn: "18 Jul, 2025",
        priority: "Low",
        status: "Closed",
        lastUpdated: "3 days ago",
    },
    {
        ticketId: "#T-3641",
        submittedBy: "Kunal M.",
        requested: "Organisation",
        issueType: "Compliance Report Missing",
        raisedOn: "15 Jul, 2025",
        priority: "High",
        status: "Open",
        lastUpdated: "4 days ago",
    },
    {
        ticketId: "#T-3610",
        submittedBy: "Olivia W.",
        requested: "Internal",
        issueType: "Dashboard Loading Issue",
        raisedOn: "12 Jul, 2025",
        priority: "Low",
        status: "Open",
        lastUpdated: "5 days ago",
    },
    {
        ticketId: "#T-3582",
        submittedBy: "Daniel C.",
        requested: "Organisation",
        issueType: "Incorrect Payslip Format",
        raisedOn: "09 Jul, 2025",
        priority: "Medium",
        status: "Closed",
        lastUpdated: "1 week ago",
    },
    {
        ticketId: "#T-3556",
        submittedBy: "Nina B.",
        requested: "Internal",
        issueType: "Role Permission Error",
        raisedOn: "05 Jul, 2025",
        priority: "Medium",
        status: "Open",
        lastUpdated: "1 week ago",
    },
    {
        ticketId: "#T-3521",
        submittedBy: "Rahul N.",
        requested: "Organisation",
        issueType: "Payroll Processing Delay",
        raisedOn: "03 Jul, 2025",
        priority: "High",
        status: "Open",
        lastUpdated: "8 days ago",
    },
    {
        ticketId: "#T-3498",
        submittedBy: "Isabella M.",
        requested: "Internal",
        issueType: "User Role Assignment Issue",
        raisedOn: "01 Jul, 2025",
        priority: "Medium",
        status: "Closed",
        lastUpdated: "9 days ago",
    },
    {
        ticketId: "#T-3462",
        submittedBy: "Vikram S.",
        requested: "Organisation",
        issueType: "Overtime Calculation Error",
        raisedOn: "28 Jun, 2025",
        priority: "High",
        status: "Open",
        lastUpdated: "10 days ago",
    },
    {
        ticketId: "#T-3437",
        submittedBy: "Hannah T.",
        requested: "Internal",
        issueType: "Notification Emails Not Sent",
        raisedOn: "26 Jun, 2025",
        priority: "Medium",
        status: "Open",
        lastUpdated: "11 days ago",
    },
    {
        ticketId: "#T-3415",
        submittedBy: "Aditya R.",
        requested: "Organisation",
        issueType: "Incorrect Tax Slab Applied",
        raisedOn: "24 Jun, 2025",
        priority: "High",
        status: "Closed",
        lastUpdated: "12 days ago",
    },
    {
        ticketId: "#T-3389",
        submittedBy: "Laura P.",
        requested: "Internal",
        issueType: "SSO Login Failure",
        raisedOn: "22 Jun, 2025",
        priority: "High",
        status: "Open",
        lastUpdated: "13 days ago",
    },
    {
        ticketId: "#T-3354",
        submittedBy: "Mohit G.",
        requested: "Organisation",
        issueType: "Bonus Payout Not Reflected",
        raisedOn: "20 Jun, 2025",
        priority: "Medium",
        status: "Open",
        lastUpdated: "2 weeks ago",
    },
    {
        ticketId: "#T-3328",
        submittedBy: "Charlotte E.",
        requested: "Internal",
        issueType: "Audit Log Missing Entries",
        raisedOn: "18 Jun, 2025",
        priority: "Low",
        status: "Closed",
        lastUpdated: "2 weeks ago",
    },
    {
        ticketId: "#T-3291",
        submittedBy: "Suresh K.",
        requested: "Organisation",
        issueType: "Employee Exit Settlement Issue",
        raisedOn: "15 Jun, 2025",
        priority: "High",
        status: "Open",
        lastUpdated: "3 weeks ago",
    },
    {
        ticketId: "#T-3267",
        submittedBy: "Benjamin H.",
        requested: "Internal",
        issueType: "Report Export Failed",
        raisedOn: "12 Jun, 2025",
        priority: "Low",
        status: "Open",
        lastUpdated: "3 weeks ago",
    }
];

export const notifications: Notifications[] = [
    {
        id: "1",
        title: "Lorem ipsum dolor sit amet consectetur. At.",
        description: "Lorem ipsum dolor sit amet consectetur. Elementum.",
        time: "3 mins ago",
    },
    {
        id: "2",
        title: "Lorem ipsum dolor sit amet consectetur.",
        description: "Lorem ipsum dolor sit amet consectetur. Sed ac.",
        time: "3 mins ago",
    },
];

export const users: User[] = [
    {
        id: "UID-1034",
        name: "Mike Willer",
        email: "mike@bostonpayroll.com",
        role: "Payroll Manager",
        client: "Bluewave Retail",
        status: "Active",
        lastLogin: "Jul 29 - 11:10 AM",
    },
    {
        id: "UID-1035",
        name: "Rahul Menon",
        email: "rahul@bostonpayroll.com",
        role: "HR Admin",
        client: "Liberty Healthcare",
        status: "Active",
        lastLogin: "Jul 28 - 04:02 PM",
    },
    {
        id: "UID-1036",
        name: "Juliet Owens",
        email: "juliet@bostonpayroll.com",
        role: "Client Admin",
        client: "Greenfield Finance",
        status: "Active",
        lastLogin: "Jul 29 - 09:14 AM",
    },
    {
        id: "UID-1037",
        name: "Carlos Mejia",
        email: "carlos@bostonpayroll.com",
        role: "Accountant",
        client: "Bright Solutions LLC",
        status: "Inactive",
        lastLogin: "Jul 27 - 03:30 PM",
    },
    {
        id: "UID-1038",
        name: "Fiona Maseko",
        email: "fiona@bostonpayroll.com",
        role: "HR Specialist",
        client: "Silverlake Technologies",
        status: "Active",
        lastLogin: "Jul 29 - 10:30 AM",
    },
    {
        id: "UID-1039",
        name: "Li Wei",
        email: "li.wei@bostonpayroll.com",
        role: "Payroll Coordinator",
        client: "Horizon Contractors",
        status: "Pending",
        lastLogin: "Jul 28 - 07:47 AM",
    },
    {
        id: "UID-1040",
        name: "Dipo Adeniran",
        email: "dipo@bostonpayroll.com",
        role: "Finance Manager",
        client: "Redwood Logistics",
        status: "Inactive",
        lastLogin: "Jul 18 - 05:40 PM",
    },
    {
        id: "UID-1041",
        name: "Clara King",
        email: "clara@bostonpayroll.com",
        role: "Subscription Owner",
        client: "Apex Hospitality",
        status: "Pending",
        lastLogin: "Jul 29 - 08:15 AM",
    },
    {
        id: "UID-1042",
        name: "Ethan Brooks",
        email: "ethan@bostonpayroll.com",
        role: "Payroll Analyst",
        client: "Northstar Manufacturing",
        status: "Active",
        lastLogin: "Jul 30 - 09:05 AM",
    },
    {
        id: "UID-1043",
        name: "Sara Ahmed",
        email: "sara@bostonpayroll.com",
        role: "Compliance Officer",
        client: "Union Financial Group",
        status: "Active",
        lastLogin: "Jul 30 - 11:45 AM",
    },
];
